version: '3.7'
services:
  main:
    image: nathanforester321/main:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
         - USERNAME=${USERNAME}
         - PASSWORD=${}
         - ENDPOINT=
         - 
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 1