version: '3.7'
services:
  main:
    image: vishals321/main:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
         - USERNAME=${USERNAME}
         - PASSWORD=${PASSWORD}
         - ENDPOINT=${ENDPOINT}
         - NAME=${NAME} 
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 1